### ISSUE TITLE
Bloquer la gesture de back depuis le menu

### ISSUE THREAD

**Issue by lenteurman** [FamilinkTipunch/Familink#53]
On peut se déconnecter depuis le menu avec une gesture de slide de la gauche.
Il faudrait corriger cela afin d'éviter une mauvaise manip de l'utilisateur.

**Comment by erjondev** [comment]
Sur quelle platforme ?

**Comment by lenteurman** [comment]
sur iOS , sur le simulateur. 2 manips à interdire: le slide depuis login et le slide depuis accueil
