### ISSUE TITLE
Warning répété en boucle !

### ISSUE THREAD

**Issue by erjondev** [FamilinkTipunch/Familink#54]
Le warning suivant est répété en boucle quel que soit la page ouverte.
Testé sur Android uniquement.

> Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.
> 
> Please check the code for the LoadingScreen component.

**Comment by lenteurman** [comment]
même chose sur iOS simulator.
